export const mockProjects = [
  {
    id: 1,
    name: " Cumulus Tee",
    status: "active",
    happiness: "happy",
    image: "/cumulustee.jpg",
    details: {
      recipient: "myself",
      size: "M",
      gauge: "28/10",
      needleSize: "3.0mm",
      startDate: "03-03-2023",
      endDate: "",
    },
    pattern: "",
    yarn: {
      brand: "kfo",
      skeins: 4,
      Type: "silk",
      gramm: 300,
      color: "green",
      meter: 1000,
    },
    note: "",
  },
  {
    id: 2,
    name: " Sophie Scarf",
    status: "completed",
    happiness: "happy",
    image: "/sophiescarf.jpg",
    details: {
      recipient: "myself",
      size: "",
      gauge: "10/10",
      needleSize: "5.0mm",
      startDate: "01-03-2023",
      endDate: "20-03-2023",
    },
    pattern: "",
    yarn: {
      brand: "Regia",
      skeins: 1,
      type: "75% Schurwolle und 25% Polyamid",
      gramm: 100,
      color: "Brasil Salvador",
      meter: 300,
    },
    note: "",
  },
  {
    id: 3,
    name: "Socks",
    status: "completed",
    happiness: "happy",
    image: "/socks.jpg",
    details: {
      recipient: "Papa",
      size: "",
      gauge: "10/10",
      needleSize: "5.0mm",
      startDate: "01-03-2023",
      endDate: "20-03-2023",
    },
    pattern: "",
    yarn: {
      brand: "Regia",
      skeins: 1,
      type: "75% Schurwolle und 25% Polyamid",
      gramm: 30,
      color: "Brasil Salvador",
      meter: 150,
    },
    note: "",
  },
];
